tick_kosdaq = [
  {
    "no"             : 0,
    "col_nm_eng"     : "TRADE_DATE",
    "col_nm_kor"     : "일자",
    "col_description": "거래가 발생한 날짜",
    "datatype" : str,
  },
  {
    "no"             : 1,
    "col_nm_eng"     : "BLKTRD_TP_CD",
    "col_nm_kor"     : "대량매매구분코드",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 2,
    "col_nm_eng"     : "REGUL_OFFHR_TP_CD",
    "col_nm_kor"     : "정규시간외구분코드",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 3,
    "col_nm_eng"     : "ISIN_CODE",
    "col_nm_kor"     : "종목코드",
    "col_description": "거래종목의 표준코드",
    'datatype' : str,
  },
  {
    "no"             : 4,
    "col_nm_eng"     : "JONG_INDEX",
    "col_nm_kor"     : "종목인덱스",
    "col_description": "해당시장에서의 종목index",
    'datatype' : str,
  },
  {
    "no"             : 5,
    "col_nm_eng"     : "TRD_NO",
    "col_nm_kor"     : "체결번호",
    "col_description": "거래 일련번호",
    'datatype' : int, 
  },
  {
    "no"             : 6,
    "col_nm_eng"     : "TRD_PRC",
    "col_nm_kor"     : "체결가격",
    "col_description": "체결된 가격",
    'datatype' : float,
  },
  {
    "no"             : 7,
    "col_nm_eng"     : "TRDVOL",
    "col_nm_kor"     : "체결수량",
    "col_description": "체결된 수량",
    'datatype' : float,
  },
  {
    "no"             : 8,
    "col_nm_eng"     : "TRD_TP_CD",
    "col_nm_kor"     : "체결유형코드",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 9,
    "col_nm_eng"     : "TRD_DD",
    "col_nm_kor"     : "체결일자",
    "col_description": "체결이 발생한 일자",
    'datatype' : str,
  },
  {
    "no"             : 10,
    "col_nm_eng"     : "TRD_TM",
    "col_nm_kor"     : "체결시각",
    "col_description": "체결이 발생한 시각",
    'datatype' : str,
  },
  {
    "no"             : 11,
    "col_nm_eng"     : "NBMM_TRD_PRC",
    "col_nm_kor"     : "근월물체결가격",
    "col_description": "사용하지 않음",
    'datatype' : float,
  },
  {
    "no"             : 12,
    "col_nm_eng"     : "FUTRMM_TRD_PRC",
    "col_nm_kor"     : "원월물체결가격",
    "col_description": "사용하지 않음",
    'datatype' : float,
  },
  {
    "no"             : 13,
    "col_nm_eng"     : "BID_MBR_NO",
    "col_nm_kor"     : "매수회원번호",
    "col_description": "거래소에 등록된 회원사번호",
    'datatype' : str,
  },
  {
    "no"             : 14,
    "col_nm_eng"     : "BIDORD_TP_CD",
    "col_nm_kor"     : "매수호가유형코드",
    "col_description": {
      "1": "시장가 (Market)",
      "2": "지정가 (Limit)",
      "I": "조건부지정가 (Limit To Market)",
      "V": "경쟁대량 (현물만 해당, 값 변경 : 3->V)",
      "X": "최유리지정가",
      "Y": "최우선지정가 (현물만 해당)"
    },
    'datatype' : str,
  },
  {
    "no"             : 15,
    "col_nm_eng"     : "BID_TRSTK_STAT_ID",
    "col_nm_kor"     : "매수자사주신고서ID",
    "col_description": "자사주거래만 해당",
    'datatype' : str,
  },
  {
    "no"             : 16,
    "col_nm_eng"     : "BID_TRSTK_TRD_METHD_CD",
    "col_nm_kor"     : "매수자사주매매방법코드",
    "col_description": "자사주거래만 해당",
    'datatype' : str,
  },
  {
    "no"             : 17,
    "col_nm_eng"     : "BID_ASK_TP_CD",
    "col_nm_kor"     : "매수매도유형코드",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 18,
    "col_nm_eng"     : "BID_TRST_PRINC_TP_CD",
    "col_nm_kor"     : "매수위탁자기구분코드",
    "col_description": { "10": "위탁매매", "30": "자기매매" },
    'datatype' : str,
  },
  {
    "no"             : 19,
    "col_nm_eng"     : "BID_TRSTCOM_NO",
    "col_nm_kor"     : "매수위탁사번호",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 20,
    "col_nm_eng"     : "BID_PT_TP_CD",
    "col_nm_kor"     : "매수PT구분코드",
    "col_description": {
      "00": "일반",
      "10": "차익거래",
      "11": "지수차익거래",
      "12": "주식차익거래",
      "13": "ETF차익거래이면서 지수비차익거래인 경우",
      "14": "ETF차익거래이면서 지수비차익거래가 아닌 경우",
      "15": "DR차익거래",
      "16": "KDR차익거래",
      "20": "헤지거래",
      "21": "ELW헤지거래",
      "22": "선물헤지거래",
      "23": "ETF 헤지거래",
      "24": "장외파생상품 헤지거래",
      "30": "비차익거래",
      "31": "지수비차익거래",
      "40": "설정거래",
      "41": "ETF설정거래이면서 지수비차익거래인 경우",
      "42": "ETF설정거래이면서 지수비차익거래가 아닌 경우"
    },
    'datatype' : str,
  },
  {
    "no"             : 21,
    "col_nm_eng"     : "BID_INVST_TP_CD",
    "col_nm_kor"     : "매수투자자구분코드",
    "col_description": {
      "1000": "증권회사 및 선물회사",
      "2000": "보험회사",
      "3000": "자산운용회사 및 투자회사",
      "3100": "사모펀드",
      "4000": "은행 (자산운용회사의 신탁재산은 자산운용회사로 분류)",
      "5000": "종합금융회사, 상호저축은행",
      "6000": "연금, 기금 및 공제회",
      "7000": "국가, 지방자치단체 및 국제기구",
      "7100": "기타법인",
      "8000": "개인"
    },
    'datatype' : str,
  },
  {
    "no"             : 22,
    "col_nm_eng"     : "BID_FORNINVST_TP_CD",
    "col_nm_kor"     : "매수외국인투자자구분코드",
    "col_description": {
      "00": "외국인아님",

      "10": "외국인(거주)",
      "11": "ID있는외국인 (거주)",
      "12": "ID없는외국인 (거주)",

      "20": "외국인(비거주)",
      "21": "ID있는외국인 (비거주)",
      "22": "ID없는외국인 (비거주)"
    },
    'datatype' : str,
  },
  {
    "no"             : 23,
    "col_nm_eng"     : "BIDORD_ACPT_NO",
    "col_nm_kor"     : "매수호가접수번호",
    "col_description": "호가접수일련번호",
    'datatype' : int,
  },
  {
    "no"             : 24,
    "col_nm_eng"     : "ASK_MBR_NO",
    "col_nm_kor"     : "매도회원번호",
    "col_description": "거래소에 등록된 회원사번호",
    'datatype' : str,
  },
  {
    "no"             : 25,
    "col_nm_eng"     : "ASKORD_TP_CD",
    "col_nm_kor"     : "매도호가유형코드",
    "col_description": "매수호가유형코드참조",
    'datatype' : str,
  },
  {
    "no"             : 26,
    "col_nm_eng"     : "ASK_TRSTK_STAT_ID",
    "col_nm_kor"     : "매도자사주신고서ID",
    "col_description": "자사주거래만 해당",
    'datatype' : str,
  },
  {
    "no"             : 27,
    "col_nm_eng"     : "ASK_TRSTK_TRD_METHD_CD",
    "col_nm_kor"     : "매도자사주매매방법코드",
    "col_description": "자사주거래만 해당",
    'datatype' : str,
  },
  {
    "no"             : 28,
    "col_nm_eng"     : "ASK_ASK_TP_CD",
    "col_nm_kor"     : "매도매도유형코드",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 29,
    "col_nm_eng"     : "ASK_TRST_PRINC_TP_CD",
    "col_nm_kor"     : "매도위탁자기구분코드",
    "col_description": { "10": "위탁매매", "30": "자기매매" },
    'datatype' : str,
  },
  {
    "no"             : 30,
    "col_nm_eng"     : "ASK_TRSTCOM_NO",
    "col_nm_kor"     : "매도위탁사번호",
    "col_description": "사용하지 않음",
    'datatype' : str,
  },
  {
    "no"             : 31,
    "col_nm_eng"     : "ASK_PT_TP_CD",
    "col_nm_kor"     : "매도PT구분코드",
    "col_description": "매수PT구분코드참조",
    'datatype' : str,
  },
  {
    "no"             : 32,
    "col_nm_eng"     : "ASK_INVST_TP_CD",
    "col_nm_kor"     : "매도투자자구분코드",
    "col_description": "매수투자자구분코드참조",
    'datatype' : str,
  },
  {
    "no"             : 33,
    "col_nm_eng"     : "ASK_FORNINVST_TP_CD",
    "col_nm_kor"     : "매도외국인투자자구분코드",
    "col_description": "매수외국인투자자구분코드참조",
    'datatype' : str,
  },
  {
    "no"             : 34,
    "col_nm_eng"     : "ASKORD_ACPT_NO",
    "col_nm_kor"     : "매도호가접수번호",
    "col_description": "매수호가접수번호참조",
    'datatype' : str,
  },
  {
    "no"             : 35,
    "col_nm_eng"     : "OPEN_PRICE",
    "col_nm_kor"     : "시가",
    "col_description": "체결당시의 시가",
    'datatype' : float,
  },
  {
    "no"             : 36,
    "col_nm_eng"     : "HIGH_PRICE",
    "col_nm_kor"     : "고가",
    "col_description": "체결당시의 고가",
    'datatype' : float,
  },
  {
    "no"             : 37,
    "col_nm_eng"     : "LOW_PRICE",
    "col_nm_kor"     : "저가",
    "col_description": "체결당시의 저가",
    'datatype' : float,
  },
  {
    "no"             : 38,
    "col_nm_eng"     : "LST_PRC",
    "col_nm_kor"     : "직전가격",
    "col_description": "사용하지 않음",
    'datatype' : float,
  },
  {
    "no"             : 39,
    "col_nm_eng"     : "ACC_TRDVOL",
    "col_nm_kor"     : "누적체결수량",
    "col_description": "체결당시까지누적된 체결수량",
    'datatype' : float,
  },
  {
    "no"             : 40,
    "col_nm_eng"     : "ACC_AMT",
    "col_nm_kor"     : "누적거래대금",
    "col_description": "체결당시까지누적된 거래대금",
    'datatype' : float,
  },
  {
    "no"             : 41,
    "col_nm_eng"     : "LST_ASKBID_TP_CD",
    "col_nm_kor"     : "최종매도매수구분코드",
    "col_description": { "1": "매도", "2": "매수" },
    'datatype' : str,
  },
  {
    "no"             : 42,
    "col_nm_eng"     : "LP_HD_QTY",
    "col_nm_kor"     : "LP보유수량",
    "col_description": "LP호가 집계후 LP보유수량",
    'datatype' : float,
  },
  {
    "no"             : 43,
    "col_nm_eng"     : "DATA_TYPE",
    "col_nm_kor"     : "데이터구분",
    "col_description": "내부사용값",
    'datatype' : str,
  },
  {
    "no"             : 44,
    "col_nm_eng"     : "MSG_SEQ",
    "col_nm_kor"     : "메세지일련번호",
    "col_description": "내부사용값",
    'datatype' : int,
  },
  {
    "no"             : 45,
    "col_nm_eng"     : "BID_PROGM_ORD_DECL_TP_CD",
    "col_nm_kor"     : "매수프로그램호가신고구분코드",
    "col_description": {
      "0"    : "해당없음",
      "1"    : "사전신고",
      "2"    : "사후신고",
      "Space": "경쟁대량매매"
    },
    'datatype' : str,
  },
  {
    "no"             : 46,
    "col_nm_eng"     : "ASK_PROGM_ORD_DECL_TP_CD",
    "col_nm_kor"     : "매도프로그램호가신고구분코드",
    "col_description": {
      "0"    : "해당없음",
      "1"    : "사전신고",
      "2"    : "사후신고",
      "Space": "경쟁대량매매"
    },
    'datatype' : str,
  },
  {
    "no"             : 47,
    "col_nm_eng"     : "BRD_ID",
    "col_nm_kor"     : "보드ID",
    "col_description": "내부사용값",
    'datatype' : str,
  },
  {
    "no"             : 48,
    "col_nm_eng"     : "SESSION_ID",
    "col_nm_kor"     : "세션ID",
    "col_description": "내부사용값",
    'datatype' : str,
  },
  {
    "no"             : 49,
    "col_nm_eng"     : "DYNMC_UPLMTPRC",
    "col_nm_kor"     : "실시간상한가",
    "col_description": "가격급변시 사용하는 실시간상한가",
    'datatype' : float,
  },
  {
    "no"             : 50,
    "col_nm_eng"     : "DYNMC_LWLMTPRC",
    "col_nm_kor"     : "실시간하한가",
    "col_description": "가격급변시 사용하는 실시간하한가",
    'datatype' : float,
  }
]
